//
// Created by david on 4/2/20.
//

#ifndef CONTRA_CONSTS_H
#define CONTRA_CONSTS_H

#define WINDOW_WIDTH 1020
#define WINDOW_HEIGHT 896
#define PIXELS_ZOOM 4

#define RENDERING_LAYERS 3
#define RENDERING_LAYER_ENEMIES 0
#define RENDERING_LAYER_PLAYER 1
#define RENDERING_LAYER_BULLETS 2

#endif //CONTRA_CONSTS_H
