//
// Created by david on 4/2/20.
//

#ifndef CONTRA_CONSTS_H
#define CONTRA_CONSTS_H

#define WINDOW_WIDTH 1020
#define WINDOW_HEIGHT 896
#define RENDERING_MARGINS 200
#define PIXELS_ZOOM 4

#define MAX_DEFAULT_BULLETS 4
#define MAX_FIRE_BULLETS 4
#define MAX_MACHINE_GUN_BULLETS 6
#define MAX_SPREAD_BULLETS 10
#define MAX_LASER_BULLETS 5
#define MAX_NPC_BULLETS 40

#define PLAYER_COLLISION_LAYER 0
#define NPCS_COLLISION_LAYER 1

#define LIFE_SPRITE_WIDTH 8
#define LIFE_SPRITE_HEIGHT 16
#define LIFE_SPRITE_MARGIN 2
#define LIFE_SPRITE_X 193
#define LIFE_SPRITE_Y 0

#define RENDERING_LAYERS 3
#define RENDERING_LAYER_ENEMIES 0
#define RENDERING_LAYER_PLAYER 1
#define RENDERING_LAYER_BULLETS 2

#define PLAYER_SPEED 55
#define PLAYER_JUMP 200

#define PICKUP_SPEED 50

#endif //CONTRA_CONSTS_H
